### ISSUE TITLE
Users should be able to start continuous Pomodoros

### ISSUE THREAD

**Issue by andreidimaano** [andreidimaano/Calcifer#12]
### Function:

`c: pomodoro m break n`

where m is the amount of focus time and n is the amount of break time

### Complementary Functions:

`c: stop`

I already have a command - `c: cancel`, but including a c: stop command with the same functionality would be helpful.

automatic stop

I need to be able to automatically stop the Pomodoro after 5 or 10 loops. Some arbitrary number so that I don't overload the server.

`c: status`

Users need to be able to see the status of their break/study time.

**Comment by andreidimaano** [comment]
UPDATE 1/19/2021
I added a break time to the parser but I haven't run any automated tests so it may be broken. Also, you can't actually use a break time just yet :))

**Comment by han-codes** [comment]
Excited to have some type of break time :). Even if we just manually create a break time with c: break n

**Comment by andreidimaano** [comment]
UPDATE 1/26/2021

Break time officially added - continuous pomodoros will not be implemented due to the way setTimeout() interacts with loops.
