### ISSUE TITLE
Group Pomodoro Tasks

### ISSUE THREAD

**Issue by andreidimaano** [andreidimaano/Calcifer#20]
#15 
Group Pomodoro

Version 1
Pros: Only certain people get notified.
Cons: Lots of overhead - tracking arrays of people that react to messages, more data in database

Version 2
Pros: Easy to implement, less overhead
Cons: Server Mods must implement a group pomodoro and individual pomodoro channel - other wise everyone in the voice channel of the person who started the group pomodoro will be notified.

I will most likely implement Version 2, Version 2 might work in general - Every server must implement two Pomodoro Channels - individual and group pomodoros. I think I will leave it up to the servers to implement this correctly. 

## Version 1:
Database:
- [ ] Create a CurrentPomodoros Collection (see bottom)
- [ ] Create a Pomodoro in the database
- [ ] Read a Pomodoro in the database
- [ ] Update Pomodoro array of users
- [ ] Delete Pomodoro after minutes have been attributed

CurrentPomodoros:
- author
- array of users
- work time
- break time

useful links: [remove array element in mongodb ](https://stackoverflow.com/questions/16959099/how-to-remove-array-element-in-mongodb)

## Version 2:
We will be unable to check if a user is part of a group pomodoro and an individual pomodoro, so technically you can double your time by doing a group pom and an individual pom at once.

- [x] Create a group pomodoros Collection that stores the channel Id
- [x] Users cannot start a group pomodoro unless they are in the voice channel for group pomodoros
- [x] At the end of the pomodoro,  loop through all users in the "group pomodoro" voice channel. For each user 1. add them to the notification message and 2. update total minutes studied in database. (see bottom)
- [x] Implement ```CreateGroup()``` 
- [x] Implement ```DeleteGroup()```
- [x] Implement ```GroupExists()``` - if group pomodoro has started in a text channel, then we will not allow any users to start another group pomodoro
- [x] Check that a group pomodoro has started in the correct text channel.
- [x] Refactor Pomodoro Timer Function
```
endPomodoro() {
    let usersToPing: string;
    users.forEach((user) => {
        1. usersToPing.concat(user.discordTag, ' ');
        2. updateDatabase(user, minutes);
    }
    message.channel.send(endEmbed(usersToPing));
}
```
```
message.member.voice.channel.members
message.member.voice.channelID
message.member.roles.cache
```

**Comment by Losstheboss** [comment]
Thought of a challenge - I wonder in JS if you can check to see who's in the new voice group for this as well so the group lead can make a single command? 🤔

**Comment by andreidimaano** [comment]
> Thought of a challenge - I wonder in JS if you can check to see who's in the new voice group for this as well so the group lead can make a single command? 🤔

https://discord.js.org/#/docs/main/stable/class/VoiceChannel?scrollTo=members

It's actually possible! as long as the user stays connected to the voice channel.

**Comment by Losstheboss** [comment]
One last idea in related to this... To save individuals doing the math... maybe a /syncup command to join the group poms if mid-joining
