### ISSUE TITLE
Calcifer does not cancel poms

### ISSUE THREAD

**Issue by middlymedley** [andreidimaano/Calcifer#24]
Seems that calcifer is not handling cancel pom requests. The little guy will respond that the pom is cancelled but still send out a ping at the completion of the pom despite it already having been cancelled.
![image](https://user-images.githubusercontent.com/79497291/108802910-513d8680-7567-11eb-9b0e-2517fce6deea.png)

**Comment by andreidimaano** [comment]
Fixed! It was a small change in the code. I'll push the hotfix in a couple of hours when people finish working

**Comment by middlymedley** [comment]
huzzah! :)) Thank bro!
