### ISSUE TITLE
Breaks with group pomodoros - Enhancement

### ISSUE THREAD

**Issue by han-codes** [andreidimaano/Calcifer#32]
Individual poms you're able to set break times.
Would be great to be able to set breaks for group poms.
`c: group pom pom break 10`
`c: group 50 break 10`

**Comment by andreidimaano** [comment]
Update 3/24/2021
Just finished implementing :) 
Will Push Updates soon

**Comment by han-codes** [comment]
Currently experiencing forced breaks of 25 min when doing a group pom

**Comment by han-codes** [comment]
In `c: help` could there be a `c: group [number] break [number]` command description?
